"""
gcode_utils.py
Shared G-code helper functions for the Sovol SV02 pen plotter.
"""

import math


def gcode_header(settings: dict) -> list[str]:
    """Return standard G-code header lines."""
    return [
        "; Sovol SV02 Pen Plotter G-code",
        "; Generated by Sovol Pen Plotter Web App",
        f"; Canvas: {settings['canvas_x']}x{settings['canvas_y']}mm",
        f"; Z_DRAW={settings['z_draw']}  Z_HOP={settings['z_hop']}",
        ";",
        "G21 ; mm units",
        "G90 ; absolute positioning",
        "G28 X Y ; home X and Y ONLY",
        f"G0 Z{settings['z_hop']:.3f} F{settings['feed_travel']} ; pen up",
        "",
    ]


def gcode_footer(settings: dict) -> list[str]:
    """Return standard G-code footer lines."""
    return [
        "",
        "; === FOOTER ===",
        f"G0 Z{settings['z_hop'] + 5:.3f} F{settings['feed_travel']} ; raise pen safely",
        f"G0 X{settings['offset_x']:.3f} Y{settings['offset_y']:.3f} F{settings['feed_travel']} ; return to origin",
        "M84 ; disable steppers",
    ]


def pen_down(settings: dict) -> str:
    return f"G0 Z{settings['z_draw']:.3f} F{settings['feed_travel']} ; pen down"


def pen_up(settings: dict) -> str:
    return f"G0 Z{settings['z_hop']:.3f} F{settings['feed_travel']} ; pen up"


def travel_to(x: float, y: float, settings: dict) -> str:
    return f"G0 X{x:.3f} Y{y:.3f} F{settings['feed_travel']}"


def draw_to(x: float, y: float, settings: dict) -> str:
    return f"G1 X{x:.3f} Y{y:.3f} F{settings['feed_draw']}"


def arc_cw(x: float, y: float, i: float, j: float, settings: dict) -> str:
    return f"G2 X{x:.3f} Y{y:.3f} I{i:.3f} J{j:.3f}"


def arc_ccw(x: float, y: float, i: float, j: float, settings: dict) -> str:
    return f"G3 X{x:.3f} Y{y:.3f} I{i:.3f} J{j:.3f}"


def estimate_time(path_length_mm: float, settings: dict) -> int:
    """Estimate draw time in seconds."""
    draw_time = (path_length_mm / settings["feed_draw"]) * 60
    travel_time = (path_length_mm * 0.3 / settings["feed_travel"]) * 60
    return int(draw_time + travel_time)


def path_length(points: list) -> float:
    """Calculate total length of a path in mm."""
    total = 0.0
    for i in range(1, len(points)):
        dx = points[i][0] - points[i - 1][0]
        dy = points[i][1] - points[i - 1][1]
        total += math.hypot(dx, dy)
    return total


DEFAULT_SETTINGS = {
    "z_draw": 0.0,
    "z_hop": 3.0,
    "feed_draw": 1500,
    "feed_travel": 3000,
    "canvas_x": 200,
    "canvas_y": 160,
    "offset_x": 40,
    "offset_y": 40,
}
